### ISSUE TITLE
Issue on import

### ISSUE THREAD

**Issue by EJH2** [vaibhav-y/py-strawpoll#1]
So, I installed the module, and now every time I try to import it I get:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python35\lib\site-packages\strawpoll\__init__.py", line 1, in <module>
    from strawpoll_api_reader import StrawpollAPIReader
ImportError: No module named 'strawpoll_api_reader'`
I would love to use this module, so please get back to me as soon as you can.

**Comment by envp** [comment]
Thanks for taking the time to report the issue. I haven't had the opportunity to test it myself but I think it may be because of the difference between python 3 & 2's import functionality.

Can you try one of the following ?
1.  You can use Python's [2to3 library](https://docs.python.org/2/library/2to3.html) to port the code to Python 3.x for your usage
2. Downgrade to the last Python 2 where this will work.

I'm in the process of re-writing this (preserving the existing API structure as much as possible) but have been procrastinating a lot.

Thanks for reporting the issue :+1:

**Comment by EJH2** [comment]
Fixed the import issue with 2to3, but now all Strawpolls return None, even if I'm using the examples in the Readme. Just a heads-up.

**Comment by envp** [comment]
Thanks! 
I'll keep that in mind
